---
#title: "Información sobre el curso"
toc: true
#self-contained: true
---


::: {.callout-note appearance="default" icon="false"}
#### Logística

En el curso utilizaremos ordenadores y algunos programas y servicios informáticos. En esta sección explicaré los detalles de instalación y/o uso

:::

<br><br>


### Programas
::: {.callout-note appearance="minimal" icon="false"}


-   En el curso usaremos principalmente **3 programas**. Principalmente usaremos  [R](https://cran.r-project.org/){target="_blank"} a través de [RStudio](https://www.rstudio.com/products/rstudio/download/#download){target="_blank"}. También usaremos [Quarto](https://quarto.org/).

-   Se recomienda tener instaladas **versiones recientes** de los 3 programas. Tienes instrucciones de instalación más abajo

-   Es muy-muy conveniente acudir al curso con **tu propio ordenador** ([y un ratón]{.underline})

:::


## Programas (instalación)

::: {.callout-important collapse="false" appearance="default" icon="false"}
## Instalación de R, RStudio y Quarto

-   En el curso usaremos 3 programas: R, RStudio y Quarto, así que tenemos que instalarlos

-   Has de instalar los programas en este orden:

    1.  R: <https://cran.r-project.org/>{target="_blank"}

    2.  RStudio: <https://posit.co/download/rstudio-desktop/>{target="_blank"}
    
    3. Quarto: <https://quarto.org/docs/download/>{target="_blank"}. En realidad, si has instalado recientemente Rstudio, no hace falta que instales Quarto, ya que las últimas versiones de RStudio traen Quarto 1.9 ya incorporado.

-   Para ello, solamente has de descargar las versiones de los instaladores adecuadas para tu sistema operativo
:::



::: {.callout-important collapse="false" appearance="default" icon="false"}
## Instalación de paquetes

- En el curso también usaremos algunos paquetes de R, así que tendremos que instalarlos 

- Los paquetes se han de instalar después de haber instalado los 3 programas (R, RStudio y Quarto)

- Los paquetes [no son necesarios para el primer día del curso]{.underline}, así que, si tenéis dudas, esperaros a que Vicente os explique cómo ejecutar código R. Si aún así no sabéis cómo hacerlo, no os preocupéis, volveremos a hablar sobre ello, en clase, durante la **segunda sesión** del curso
  
:::

<br>


::: {.callout-important collapse="true" appearance="default" icon="false"}
## ¿Cómo instalar los paquetes?

- Si sabes instalarlos, perfecto!!, pero recuerda que Los paquetes no son necesarios para el primer día del curso.

- Algunos paquetes se han de compilar por lo que hay que tener las herramientas necesarias, así que:

    - Si usas Windows tendrás que instalar **Rtools**. [Aquí](https://cran.r-project.org/bin/windows/Rtools/) puedes descargarte el instalador adecuado
    
    - Si tienes un Mac, tendrás que instalar the **Xcode Command Line Tools**. Lo normal es que lo tengas ya instalado, si no fuese el caso, [aquí](https://www.makeuseof.com/install-xcode-command-line-tools/) te explican como hacerlo. Además, como nos cuentan [aquí](https://psyteachr.github.io/msc-data-skills/installingr.html), si tienes un Mac, es conveniente instalar **XQuartz**, para ello sólo tienes que buscar el instalador en <https://www.xquartz.org/>

  
- Finalmente, para instalar los paquetes que usaremos durante el curso tendremos que **ejecutar las siguientes instrucciones**:

```{r}
#| eval: false
#| code-line-numbers: false
#| code-overflow: wrap
#| code-fold: true
#| code-summary: "Código para instalar los paquetes"

#- instalación de paquetes ---------------------------------

install.packages("pak")

mys_pkgs <- c("tidyverse", "curl", "eurostat", "here", "palmerpenguins", "quantmod", "rio", "gt", "DT", "gapminder", "markdown")
pak::pkg_install(mys_pkgs)   

mys_pkgs <- c("usethis", "janitor", "ggthemes", "gganimate", "sjPlot", "refugees", "slider", "repmis", "jtools", "huxtable")
pak::pkg_install(mys_pkgs)   

mys_pkgs <- c("sf", "rcartocolor", "rmapshaper", "gtExtras", "patchwork", "magick")
pak::pkg_install(mys_pkgs)   

mys_pkgs <- c("kableExtra", "modelsummary", "widyr", "irlba", "tmap")
pak::pkg_install(mys_pkgs)

mys_pkgs <- c("GGally", "ggtext", "maps")
pak::pkg_install(mys_pkgs)  

mys_pkgs <- c("summarytools", "glin/reactable", "naniar")
pak::pkg_install(mys_pkgs)  

mys_pkgs <- c("DataExplorer", "corrr", "explore", "stargazer", "apaTables")
pak::pkg_install(mys_pkgs)   

mys_pkgs <- c("easystats", "plotly", "mapSpain")
pak::pkg_install(mys_pkgs)

mys_pkgs <- c("OECD", "rbioapi")
pak::pkg_install(mys_pkgs)

mys_pkgs <- c("openxlsx", "xlsx")
pak::pkg_install(mys_pkgs)

my_pkgs <- c("meme", "imager", "sctyner/memer", "devtools", "ggpol", "pxR", "mapproj", "WDI", "wbstats", "rJava")
pak::pkg_install(mys_pkgs)


mys_pkgs <- c("perezp44/pjpv.curso.R.2022")
pak::pkg_install(mys_pkgs)



#- finalmente, si te instalas todos los paquetes, se instalarán 324 pkg's aprox. (q ocupan 842 MB aprox.). 
#- Si tienes problemas de espacio, siempre podrás desinstalarlos o borrarlos directamente
pkgs <- pak::pkg_list()

#- normalmente tendrás 2 librerías
.libPaths()
#- en la primera tienes los pkgs de "R-base": "C:/Program Files/R/R-4.5/library"   
#- en la segunda tienes los paquetes q se instala un usuario:  "C:/Users/Usuario/AppData/Local/R/win-library/4.5"
```

:::



::: {.callout-important collapse="true" appearance="default" icon="false"}
##  Más cosas sobre instalación R

Lo que hay en esta sección [no tienes porqué ejecutarlo]{.underline}, **es sólo para tenerlo a mano por si nos hiciese falta durante el curso**


- Para chequear qué versiones del software tienes instaladas, podemos usar **en la TERMINAL** el siguiente código:

```bash
R --version         #- 4.6
rstudio --version   #- 2026.04
quarto --version    #- 1.9
```

- Para chequear si tu sistema está preparado to build packages:

```r
devtools::has_devel()    #- Your system is ready to build packages!
```

- Para instalar `tinytext` & friends, desde **la TERMINAL**:


```bash
quarto install tool tinytext
quarto install tinytex --update-path
quarto install tool chromium
```

- Algunos chequeos (desde la TERMINAL):

```bash
quarto check install
quarto check knitr
```


- Para editar preferencias de RStudio

```r
usethis::edit_rstudio_prefs()
usethis::use_blank_slate() 
```


:::

<br><br>



## Recursos

::: {.callout-note appearance="minimal" icon="false"}
- Son simplemente enlaces a servicios que (seguramente) usaremos durante el curso
:::

-   [**Etherpad**](https://etherpad.wikimedia.org/p/pjperez){target="_blank"}: durante el curso escribiremos código R. Esta etherpad nos permitirá compartir el código.

-   [**Aula Virtual de la asignatura**]({{< var my_aula_virtual >}}){target="_blank"}: como Aula Virtual es el sitio oficial de la asignatura colgaré allí los anuncios de tipo "oficial". También colgaré en Aula Virtual los detalles sobre la evaluación. 

-   [**RStudio Cloud Project**]({{< var my_posit_cloud >}}){target="_blank"}: En otros cursos este recurso nos resulto muy útil, pero ahora la versión gratuita tiene límite de tiempo así que creo que no lo usaré, pero por si acaso aquí está.

- [Cuestionario incial](cuestionario-inicial.qmd){target="_blank"}


<br><br>

## Entrega de trabajos

Durante el curso, sobre todo las primeras semanas, os mandaré tareas, algunas para resolver en el aula y otras para resolver en casa. Estas tareas, generalmente, formarán parte de la evaluación continua. Abajo tenéis las instrucciones para la entrega de las tareas:

- [Intrucciones de entrega de las tareas de la evaluación continua](./mas-cosas/04_como-entregar-las-tareas-uploader.html){target="_blank"}

<br><br>

## Materiales de clase

Durante el curso, utilizaremos diversos materiales, puedes encontrarlos en la sección [`Materiales`](03-materiales.qmd).


<br>

::: {.content-hidden}
## Instrucciones para el examen final

- [Instrucciones](./mas-cosas/instrucciones_examen.qmd){target="_blank"} y un [ejemplo](./mas-cosas/ex_final_BigData_24-25_sin-soluciones-bones.html){target="_blank"} de cómo ha de quedar más o menos el documento .html con tus respuestas
:::

