---
title: "Cuestionario inicial"
author: "Pedro J. Pérez"
#date: "Septiembre, 2023"  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

------------------------------------------------------------------------

Hola,

como os he comentado en el e-mail, antes de empezar el curso necesito saber un poco el nivel que tenéis de conocimientos de informática y programación[^1]. Por eso os pido que me **contestéis a las 10 preguntas que tenéis más abajo**. Tomároslo en serio porque igual usamos los datos del cuestionario para hacer algún análisis durante el curso.

[^1]: No te preocupes si tienes nivel bajo o muy bajo, ya que el curso empieza (casi) desde cero

**Las respuestas has de enviármelas a través del siguiente cuestionario: <https://forms.gle/Ac3EF3W1u77Zzx2u6>{target="_blank"}**



La primera parte del cuestionario consiste simplemente en poner vuestros **datos de identificación básicos**, pero además os pido: 1) vuestro **número NPA** (o número académico personal) y 2) vuestro **usuario de Github**.  

1. El **NPA** es el código que os identifica de manera única dentro de la UV. Podéis encontrar vuestro NPA en vuestra aula virtual. El NPA consta de 2 letras (en mayúsculas generalmente) y 5 números. 

2. Respecto al nombre de **usuario en Github**, tendrás que crearte una cuenta en <https://github.com/>{target="_blank"}. En Github es mejor que uses el correo de Gmail. Durante el curso usaremos está cuenta de Github, así que dedícale un tiempo a pensar tu nombre de usuario: vuestro nombre de usuario no debe tener espacios ni caracteres especiales, además de, ser escueto pero representativo y significativo para vosotros.  Por ejemplo, mi usuario de Github es `perezp44`.

<br>

Después de cumplimentar vuestros datos de identificación, tenéis que contestar a **10 preguntas**. Las primeras 8 preguntas están relacionadas con vuestros conocimientos de programación y el formato de respuesta es de texto libre^[Por favor, que las respuestas estén bien redactadas y escritas; vamos, que sean legibles]. Las **2 últimas preguntas son muy fáciles**, se trata simplemente de ver donde habéis nacido los estudiantes del curso y una canción que os guste, pero tenéis que prestar atención al formato en el que espero las respuestas.

Estas son **las 10 preguntas**:

1.  ¿Sabes de qué va, cuales son los contenidos y objetivos de la asignatura? ¿Has leído la guía docente?

2.  ¿Por qué te has matriculado en la asignatura? ¿Cuál es tu objetivo(s) en el curso?

3. ¿Cómo usas las IA's? ¿Para aprender, para redactar trabajos, ...? Recomiendame una IA que uses y que no sea muy conocida

4.  ¿Sabes qué es la ciencia de datos? Explica un poco qué es (con tus palabras)

5.  ¿Sabes qué es R? Explica un poco. ¿Sabes lo que es el "tidyverse"? Si lo sabes, explica un poco.

6.  En una escala de 0 a 10 ¿cual es tu nivel de conocimientos de R?

7.  ¿Sabes qué es html? ¿Sabes lo que es Markdown? ¿Y una ruta relativa?

8.  ¿Tienes conocimientos de programación? Si los tuvieses, indica en que lenguaje(s)

9.  País y ciudad de nacimiento. Por ejemplo: `España - Valencia` (fíjate en el orden de los 2 componentes de la repuesta y la marca de separación)

10. Dime una canción que te guste. Dame los datos en este formato: `<Grupo/Cantante> - <Canción> - <Ruta a la canción en youtube>` (fíjate en el orden de los 3 componentes de la respuesta y en la marca de separación entre componentes). Por ejemplo, en mi caso, una canción que me gusta es: `Xoel Lopéz - Reconstrucción - https://www.youtube.com/watch?v=YDi93857xFQ`

<br>

Se trata de que contestes el cuestionario [tomándotelo en serio, pero sin  volverte loco/loca con él]{.underline}

La **fecha límite** para contestar es el **{{< var my_fecha_limite_cuestionario >}} a las 23:59**.




<br>

Nos vemos en clase
